site_name: stubb
repo_url: https://github.com/deneutoy/stubb

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

nav:
  - "Getting Started": "index.md"

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: deneutoy
      repo: stubb
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - tables
